/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.guessthelogo;
import java.util.Random;

/**
 *
 * @author franc
 */
public class guesswithenhancement extends javax.swing.JFrame {
     // numbering logos to match with company answer
        Random r =  new Random();
        int randomNumber=r.nextInt(10);
        int correct=0;      
        int submitCount=0;
        final int maxSubmit=5;
    //boolean array initialised to store logos that have been used, array is initialised as false to begin with.
        boolean usedLogos[] = new boolean[10];  
    //2 string arrays created one for logo generation, the other for matching logo with 

    
    String logos []= new String[10];  
  {     logos[0]="Adobe.jpg";
        logos[1]="BP.jpg";
	logos[2]="Bic.jpg";
	logos[3]="Dominos.jpg";
	logos[4]="Linux.jpg";
	logos[5]="Lufthansa.jpg";
	logos[6]="Mitsubishi.jpg";
	logos[7]="Motorola.jpg";
	logos[8]="Rolex.jpg";
	logos[9]= "Suzuki.jpg";}
 
    String companies[]=new String[10];{
        companies[0]="Adobe";
        companies[1]="BP";
	companies[2]="Bic";
	companies[3]="Dominos";
	companies[4]="Linux";
	companies[5]="Lufthansa";
	companies[6]="Mitsubishi";
	companies[7]="Motorola";
	companies[8]="Rolex";
	companies[9]= "Suzuki";
}
   
    /**
     * Creates new form guess
     */
    public guesswithenhancement() {
        initComponents();
       
nextLogo.setEnabled(false);//next logo cannot be pressed in openeing window
feedbackTextField.setEnabled(false);//textfield can not be edited by user
resultTextField.setEnabled(false);//enhancements not visible 
TryAgain.setEnabled(false);//enhancements not visible 
ExitGame.setEnabled(false);//enhancements not visible 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        logoLabel = new javax.swing.JLabel();
        nextLogo = new javax.swing.JButton();
        companyCombo = new javax.swing.JComboBox<>();
        feedbackTextField = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ExitGame = new javax.swing.JButton();
        TryAgain = new javax.swing.JButton();
        resultTextField = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guess The Logo");

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/"+logos[randomNumber])));

        nextLogo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nextLogo.setText("Next Logo");
        nextLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextLogoActionPerformed(evt);
            }
        });

        companyCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        companyCombo.setMaximumRowCount(3);
        companyCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adobe", "BP", "Bic", "Dominos", "Linux", "Lufthansa", "Mitsubishi", "Motorola", "Rolex", "Suzuki" }));
        companyCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyComboActionPerformed(evt);
            }
        });

        feedbackTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        feedbackTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        feedbackTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackTextFieldActionPerformed(evt);
            }
        });

        submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Select Company: ");

        ExitGame.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ExitGame.setText("Exit Game");
        ExitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitGameActionPerformed(evt);
            }
        });

        TryAgain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TryAgain.setText("Try Again");
        TryAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TryAgainActionPerformed(evt);
            }
        });

        resultTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resultTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(TryAgain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitGame)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(feedbackTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(companyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feedbackTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextLogo)
                            .addComponent(submit))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitGame)
                    .addComponent(TryAgain))
                .addGap(13, 13, 13))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextLogoActionPerformed
   
   feedbackTextField.setText("");//clear text field after answer provided for previous qu
   nextLogo.setEnabled(false);//you can only press next logo button once
   companyCombo.setSelectedIndex(0);//put combo box back to first option
   submit.setEnabled(true); //make submit button availabla again
   
   //produce next random image, the loop is an attempt to prevent images from reoccuring
   //for(int i=0;i<5; i++){ 
   do{   
      randomNumber=r.nextInt(10);
       logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/"+logos[randomNumber])));
    }while(usedLogos[randomNumber]==true);
    usedLogos[randomNumber]=true;
    
    
    
   //}
// TODO add your handling code here:
    }//GEN-LAST:event_nextLogoActionPerformed

    private void companyComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyComboActionPerformed

    private void feedbackTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackTextFieldActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_feedbackTextFieldActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
 //save answers in an array 
     nextLogo.setEnabled(true);  
     submit.setEnabled(false);       
     submitCount++;
     String answer= (String) companyCombo.getSelectedItem();   
                
         if(answer.equals(companies[randomNumber])){
         correct++;
     feedbackTextField.setText("Correct!");
    }
     else {
             feedbackTextField.setText("Sorry incorrect! The correct answer is "+companies[randomNumber]);
             }
        
      //GAME OVER
      //maximum times submit can be pressed is 5 (5 questions answered)
      if(submitCount== maxSubmit){
      feedbackTextField.setText("Your score is "+correct+"/5"); //calculate score using correct count method
      logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/GameOver.png")));
      nextLogo.setEnabled(false);  
      submit.setEnabled(false); 
      companyCombo.setEnabled(false);
      
      //end of game enhancement
     int percent=correct *20;//calc %
     if(correct<5){
         TryAgain.setEnabled(true);
         ExitGame.setEnabled(true);
         
         if (correct==0||correct==1||correct==2){
         resultTextField.setText(percent+ "% You Can Do Better!!"); 
            }
         if(correct==3||correct==4){
          resultTextField.setText(percent +"% Great Attempt!!");
            }
     }
     else{
          
             fullMarks welldone=new fullMarks();
             welldone.setVisible(true);
         }
      }
     
       // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void ExitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitGameActionPerformed
      System.exit(0);

    }//GEN-LAST:event_ExitGameActionPerformed

    private void TryAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TryAgainActionPerformed
    this.setVisible(false);//close current window
    guesswithenhancement newguess = new guesswithenhancement();
    newguess.setVisible(true);
    //reopen same file, new game
// TODO add your handling code here:
    }//GEN-LAST:event_TryAgainActionPerformed

    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guesswithenhancement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guesswithenhancement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guesswithenhancement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guesswithenhancement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guesswithenhancement().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitGame;
    private javax.swing.JButton TryAgain;
    private javax.swing.JComboBox<String> companyCombo;
    private javax.swing.JTextField feedbackTextField;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton nextLogo;
    private javax.swing.JTextField resultTextField;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables


}
